### ISSUE TITLE
Model Slightly Larger in Editor

### ISSUE THREAD

**Issue by Mistro11** [thomthom/cities-skylines-sketchup-tools#2]
I used the grid from the plugin to scale the building. In SU it's well within the borders. In asset editor, it's slightly going outside the grid boundaries. I left the scale at 1.0 in the editor.

**Comment by thomthom** [comment]
It'd help with example model and screenshots here. As well as details to what type of asset you import and its config.

**Comment by Mistro11** [comment]
Ok, will do when I get home tonight.

**Comment by Mistro11** [comment]
Here are some screenshots of the test model in game and in the editor
![asseteditor_sizeresult](https://cloud.githubusercontent.com/assets/12002989/7218125/dc3311f8-e628-11e4-8ffb-52c988f5c558.jpg)
![buildingguide](https://cloud.githubusercontent.com/assets/12002989/7218126/dc34eb40-e628-11e4-89cf-df85a5b547b0.jpg)

**Comment by Mistro11** [comment]
My goodness I just realized that the guide in SU is 5x5 not 4x4. Sorry I missed that. Seems the building is scaled correctly from the script. Just the grid count that I didn't notice on the guide.
![asseteditor_fit](https://cloud.githubusercontent.com/assets/12002989/7218161/fc5071ea-e62a-11e4-947c-8005163a2cfb.jpg)
![buildingguide2](https://cloud.githubusercontent.com/assets/12002989/7218162/fc5d83bc-e62a-11e4-8999-e00bc150447e.jpg)

**Comment by thomthom** [comment]
I'll close this then. :)

(One thing I noticed in the game's Asset Editor, even when you make a 1x2 or 2x2 building and choose the same in the editor, you get a 1x4 area highlighted... not sure what that is all about...
