### ISSUE TITLE
Cant start this in Sketchup 2016

### ISSUE THREAD

**Issue by deaneau** [thomthom/cities-skylines-sketchup-tools#9]
I cant start and see this plugin in 2016

**Comment by thomthom** [comment]
Are you using Windows or Mac?

Are you using Pro or Make?

Are you seeing errors when starting SketchUp?

Is the extension listed under Preferences > Extensions?

Is the extension enabled under Preferences > Extensions?

Is the extension listed under the Extension menu?

Is the extension listed under the Toolbar list?

**Comment by deaneau** [comment]
Are you using Windows or Mac?
WIN

Are you using Pro or Make?_
Pro

Are you seeing errors when starting SketchUp?_
NO

Is the extension listed under Preferences > Extensions?_
NO

Is the extension enabled under Preferences > Extensions?_
NO

Is the extension listed under the Extension menu?_
NO

Is the extension listed under the Toolbar list?
NO

**Comment by thomthom** [comment]
> > Is the extension listed under Preferences > Extensions?
> 
> NO

Might be the installation that isn't quite right. How did you install it?

(Btw, it looks like you responded via email. That gets posted back here on GitHub and the formatting broke. I had to manually correct it. Can you respond via the GitHub website?)

**Comment by deaneau** [comment]
yes sorry i have had believe i must answer via Mail.

the installation  via preferences, like all rbz-files. with all other plugins from you i have no problems. your latest tt-lib i have installed.

**Comment by thomthom** [comment]
Hm.. Can you post a screenshot of your Plugins folder?

**Comment by deaneau** [comment]
Ok via email. i have send this to your SubD Email

**Comment by thomthom** [comment]
You can drag and drop files into the textbox here on GitHub and they get attached to the issue.

**Comment by deaneau** [comment]
solved

**Comment by thomthom** [comment]
This is very strange - I see no reason for it to not be displayed in Preferences > Extensions. Espesially if there is no error during startup.

Can you enter these lines - one by one - into the Ruby Console and return the output for each line?

`$LOADED_FEATURES.join("\n")`

`Sketchup.extensions.each { |ex| puts "#{ex.name} (#{ex.loaded?})" }`

`Sketchup.version`

`Sketchup.find_support_file('Plugins')`

**Comment by deaneau** [comment]
see next  

wow 2067 lines

**Comment by thomthom** [comment]
It looks like the text got cut off. Might have to save this to a TXT file and upload it.

**Comment by deaneau** [comment]
solved

**Comment by thomthom** [comment]
Hm... it indicates that it's not loaded. I'm not 100% sure what is going on. However, I notice you have the first release of SketchUp 2016. There has been an update to it. It fixed some loading errors. You might want to make sure you SketchUp version is up to date first.

**Comment by deaneau** [comment]
ah ok this could be the reason.

**Comment by deaneau** [comment]
Thomas problem solved. cool

the reason was an old version of Sketchup
